AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DDBTable:
    DeletionPolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        -
          AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "pk"
          KeyType: "HASH"
        -
          AttributeName: "sk"
          KeyType: "RANGE"
      SSESpecification:
        SSEEnabled: False
      ImportSourceSpecification:
        InputCompressionType: "NONE"
        InputFormat: "CSV"
        S3BucketSource:
          S3Bucket: "myS3Bucket"
          S3KeyPrefix: "myS3Prefix/foo.csv"
